version: 2.1

python_image: &python_image
  docker:
    - image: python:3.7.3-stretch

jobs:
  run-lint:
    <<: *python_image
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cd src
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            cd src
            . venv/bin/activate
            make lint

workflows:
  default:
    jobs:
      - run-lint
